% angva.m
% angular velocity and acceleration

function out=angva...
(xM,yM,xN,yN,vMx,vMy,vNx,vNy,aMx,aMy,aNx,aNy);

theta = atan((yM-yN)/(xM-xN));

dtheta = ...
 (cos(theta)*(vMy-vNy)-sin(theta)*(vMx-vNx))/...
 (sin(theta)*(yM-yN)+cos(theta)*(xM-xN));

ddtheta = ...
 (cos(theta)*(aMy-aNy)-sin(theta)*(aMx-aNx)...
 -(cos(theta)*dtheta*(yM-yN)+2*sin(theta)*(vMy-vNy)...
 -sin(theta)*dtheta*(xM-xN)...
 +2*cos(theta)*(vMx-vNx))*dtheta)/...
 (cos(theta)*(xM-xN)+sin(theta)*(yM-yN));

out = [dtheta ddtheta];
end